### ISSUE TITLE
Responses resilience on broker disconnect

### ISSUE THREAD

**Issue by olle** [olle/query-response-spring-amqp#19]
REPRODUCE: Use the https://github.com/olle/query-response-spring-amqp/tree/master/examples/singleresponse example, which provides the very minimal use of the Query/Response library, and only registers the implicit statistics response. 

This basically creates a client with a listener for messages on the `query-response` topic exchange, routed to an anonymous queue.

BUG: The connection to the response queue (anonymous) never recovers, the listener container and the broker both end up in an endless dance, where the queue can't be re-declared, nor found (404).

EXPECTED: Response listeners, should recover as defined by the Spring AMQP channling handling and listener container configuration (capabilities).

**Comment by olle** [comment]
To clarify the urgence, and target for v0.9 - **connection failures, happen!**

**Comment by olle** [comment]
I'm working on a better setup for easier and more direct steps-to-reproduce.

The tendency right now is that no queues work for listener-containers that are retained during a loss of connection with the broker. The feeling... well it's bad. Like... this probably never worked, ever.

**Comment by olle** [comment]
Leaky. Abstractions.

**Comment by olle** [comment]
The endless passive queue declaration is triggered here:

https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java#L705

Now, this is the current root of the symptoms. Now to find out the intent and reason or rhyme for an active queue declaration in the recover scenario - maybe it was never intended to work?

**Comment by garyrussell** [comment]
@olle I am not sure what you mean by

>Now to find out the intent and reason or rhyme for an active queue declaration in the recover scenario - maybe it was never intended to work?

We do a passive declaration to make sure it exists before consuming.

The way we handle this situation in the framework is to declare the `AnonymousQueue` as a `@Bean`.

Spring Boot auto-configures a `RabbitAdmin`; the admin registers itself as a `ConnectionListener` with the connection factory.

Then, when the container recovers and opens a new connection, the Admin kicks in, finds all the `Declarable` beans in the application context and registers them automatically. This all happens before the passive declaration.

For some reason, you are side-stepping all of this and doing your own declarations.

**Comment by olle** [comment]
Hi @garyrussell, thanks for your feedback. It's truly rubber-ducking deluxe!

You are absolutely right. I've been thinking about the queue-recovery all wrong. I guess I got lost in the semantics of _exclusivity_ and the current setup with a single listener per queue. There should really be no reason for the listener to actively re-declare the queue.

I'm a big fan of `auto-delete` and a failure mode that relieves the broker, whenever possible. I might look further into a _fail-fast_ variant, and re-declare in our code. I'm sure there are error handlers or an application events being published on listener or connection failures.

The goal of this project is to provide (or wrap) some capabilities as a library, so the queue declaration, and listener setup, needs to be dynamically and programmatically done for it to actually be an amenity.

If I understand correctly, it should be _enough_ to register the `Declarables` in the application context, or by some means via the `RabbitAdmin`. That totally makes sense, and up until now we've done _the most simple thing that could possibly work_ - which it didn't 😃 - quite.

In your experience, would you see that as an actual viable solution?

We've been using Spring AMQP in production for around 7 years now, and it's always been a great tool. Most of our usage have been declarative, but Query/Response is a pattern that we have observed, and are now trying to better support with this library. I hope I can spark your interest - check out the UI at least.

Again, thank you for your feedback and help.

**Comment by garyrussell** [comment]
>In your experience, would you see that as an actual viable solution?

Yes; that should work.

I didn't look at your code closely but I was a little intrigued that your README says...

>Build safer and more resilient distributed services.

...but you are using auto-delete queues and messages can easily be lost.

**Comment by olle** [comment]
> > Build safer and more resilient distributed services.
> 
> ...but you are using auto-delete queues and messages can easily be lost.

Exactly! And I want developers to have **that** awareness and discussion, up-front and early in the design/modeling process. 😃 Query/Response is supposed to be a mind-bender.

**Comment by olle** [comment]
Yes - _with a but!_ Added registration of queues and bindings to the application context via a `GenericApplicationContext`, and now the recovery works as expected.

Now, it's not without saying though, that 2-3 times, during the refactoring, I observed the queues being redeclared but not the bindings. Scary for sure, and I can't really say if it had anything to do with my code, or if there's a race-condition somewhere.

I'm using the scenario with the _singleresponse_ example, and just shutting down the broker container, and restarting it again.

This is great. Thanks again @garyrussell
