### ISSUE TITLE
Downgrade to JDK 8 for better enterprise coverage

### ISSUE THREAD

**Issue by olle** [olle/query-response-spring-amqp#28]
So, I'm thinking it's probably more or less required to support JDK 8 in order to be considered an option to a majority of enterprise projects.

I personally don't have a problem with that.

What do you think?

**Comment by maxdobler** [comment]
Yeah, let's do it.

**Comment by olle** [comment]
As time goes by... 🎶 We're at the junction where JDK 8 is no longer a priority to support. I'll take some steps in the time to come, to move the mainline to JDK 11 and deprecate builds to support 8 - preparing for JDK 17 (in a future branch).
